export const MOSTRAR_ALERTA ='MOSTRAR_ALERTA';

export const OCULTAR_ALERTA ='OCULTAR_ALERTA';



export const REGISTRO_EXITOSO ='REGISTRO_EXITOSO';

export const REGISTRO_ERROR ='REGISTRO_ERROR';

export const OBTENER_USUARIO ='OBTENER_USUARIO';

export const LOGIN_EXITOSO ='LOGIN_EXITOSO';

export const LOGIN_ERROR ='LOGIN_ERROR';

export const CERRAR_SESION ='CERRAR_SESION';



//Declaraciones
export const OBTENER_DECLARACIONES ='OBTENER_DECLARACIONES';

export const CREAR_DECLARACION ='CREAR_DECLARACION';

export const ELIMINAR_DECLARACION = 'ELIMINAR_DECLARACION' ;
